SELECT SCHEMA_NAME AS 'Base de Datos'
FROM INFORMATION_SCHEMA.SCHEMATA;

SELECT TABLE_NAME AS 'Tabla'
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'TIENDA';

SELECT COLUMN_NAME AS 'Columna', DATA_TYPE AS 'Tipo de Dato', IS_NULLABLE AS 'Nulo'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CLIENTE' AND TABLE_SCHEMA = 'TIENDA';

SELECT TABLE_NAME AS 'Tabla', CONSTRAINT_NAME AS 'Restricción', CONSTRAINT_TYPE AS 'Tipo'
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'TIENDA';

SELECT TABLE_NAME AS 'Tabla', CONSTRAINT_NAME AS 'Restricción', REFERENCED_TABLE_NAME AS 'Tabla Referenciada'
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'TIENDA' AND REFERENCED_TABLE_NAME IS NOT NULL;

