CREATE OR REPLACE TYPE tNombre AS OBJECT (
    nombre     VARCHAR2(50),
    apellido1  VARCHAR2(50),
    apellido2  VARCHAR2(50),
    
    MEMBER FUNCTION getApellidosNombre RETURN VARCHAR2,
    MEMBER FUNCTION getNombreApellidos RETURN VARCHAR2
);

CREATE OR REPLACE TYPE BODY tNombre AS
    MEMBER FUNCTION getApellidosNombre RETURN VARCHAR2 IS
    BEGIN
        RETURN apellido1 || ' ' || apellido2 || ', ' || nombre;
    END;

    MEMBER FUNCTION getNombreApellidos RETURN VARCHAR2 IS
    BEGIN
        RETURN nombre || ' ' || apellido1 || ' ' || apellido2;
    END;
END;

ALTER TABLE CLIENTE 
ADD (NOMBRECOMPLETO tNombre);

UPDATE CLIENTE
SET NOMBRECOMPLETO = tNombre('ROSA', 'PEREZ', 'DELGADO')
WHERE NIF = '11111111A';

UPDATE CLIENTE
SET NOMBRECOMPLETO = tNombre('MARIANO', 'RODOLFO', 'DEL VALL')
WHERE NIF = '22222222B';

UPDATE CLIENTE
SET NOMBRECOMPLETO = tNombre('CARLOS', 'MALDONADO', 'PEREZ')
WHERE NIF = '33333333C';

UPDATE CLIENTE
SET NOMBRECOMPLETO = tNombre('PERICO', 'DE LOS PALOTES', 'LARGOS')
WHERE NIF = '44444444C';

ALTER TABLE CLIENTE
DROP COLUMN NOMBRE;

SELECT 
    CLI.NIF, 
    CLI.NOMBRECOMPLETO.getApellidosNombre() AS NOMBRE, 
    CLI.TLF
FROM CLIENTE CLI;
